#!/bin/bash
if command -v dpkg &> /dev/null; then
  . $(dpkg -L git |grep 'completions/git$')
fi

alias gb="git branch" ; __git_complete gb _git_branch
alias gdc="git diff --cached" ; __git_complete gdc _git_diff
alias gd="git diff" ; __git_complete gd _git_diff
alias gds="git diff --stat" ; __git_complete gds _git_diff
alias gst="git status -sb" ; __git_complete gst _git_status
alias gs="git status -sb" ; __git_complete gs _git_status
alias gco="git checkout" ; __git_complete gco _git_checkout
alias ga="git add" ; __git_complete ga _git_add
alias grb="git rebase" ; __git_complete grb _git_rebase
alias gc="git commit -v" ; __git_complete gc _git_commit
alias gcr="git commit --reedit-message=HEAD^" ; __git_complete gc _git_commit
alias gca="git commit --amend" ; __git_complete gca _git_commit
alias grbi="git rebase -i" ; __git_complete grbi _git_rebase
alias gl="git log --decorate" ; __git_complete gl _git_log
alias gls="gl --stat" ; __git_complete gls _git_log
alias glp="gl -p" ; __git_complete glp _git_log
alias gr="git reset" ; __git_complete gr _git_reset
alias grh="git reset --hard" ; __git_complete grh _git_reset
alias gcp="git cherry-pick" ; __git_complete gcp _git_cherry_pick
