#!/bin/bash

export VENV_HOME="$HOME/v"

_vactCompletion()
{
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "$(ls -1 $VENV_HOME)" -- $cur) )
}

function vact()
{
  if [ -z "$1" ]; then
    if [ -f "venv/bin/activate" ]; then
      source venv/bin/activate
      return
    else
      echo "venv folder not found"
      return
    fi
  fi
  source "$VENV_HOME/$1/bin/activate"
}

complete -F _vactCompletion vact

